### ISSUE TITLE
Replace rest_condition with native DRF permission operators

### ISSUE THREAD

**Issue by sliverc** [adfinis-sygroup/timed-backend#372]
Dep `rest_condition` is not needed anymore and can be replaced with new [DRF permission operators](https://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy) which got released in DRF 3.9.

As Timed is also affected from [issue](https://github.com/encode/django-rest-framework/issues/6296) we will have to wait for 3.9.1 to implement this.

**Comment by sbor23** [comment]
This has the following restrictions:

> Note: it only supports & -and- and | -or-.

So it would mean defining complementary rules for negations such as:
```python
C(IsAuthenticated) & C(IsSuperUser) & ~C(IsDeleteOnly)
```

**Comment by sliverc** [comment]
In such cases you could create a permission class like `IsNotDelete` which would work around this.

**Comment by sliverc** [comment]
Fixed with #397
