### ISSUE TITLE
Upgrade PostgreSQL to a non EOL version

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/timed-backend#538]
As per 923f8e23f2e1e30fd43d8ee09c6fbb0d18028013 we seem to be using a PostgreSQL version that was EOLed February 13, 2020.

We should upgrade to a version that is not EOL, basically all versions >9.4 are still in support.

See here for the available versions and their support policy: https://www.postgresql.org/support/versioning/

Once updated the  Helm chart for timed also needs updating. In fact this issue surfaced during updating/implementing the chart: https://github.com/adfinis-sygroup/timed-chart/pull/9#issuecomment-610854977

**Comment by sbor23** [comment]
So you would suggest reverting 923f8e2 and going back to v9.6?

**Comment by sbor23** [comment]
As discussed in chat, we will keep this for the current prod system as the upgrade doesn't work there. We should tackle this once the new aks environment is ready

**Comment by MrStrix** [comment]
Postgres should be upgraded and tested on a newer version before releasing new content that builds on a deprecated database. 

Versions currently running in production systems should not influence the development of newer versions. Testing for newer versions should be easy without having clusters everywhere

**Comment by sbor23** [comment]
Yes of course, I will plan the upgrade path to postgres 12 right away.

**Comment by sbor23** [comment]
No changes are needed for supporting anything >9.4.
