### ISSUE TITLE
User assignment on various objects

### ISSUE THREAD

**Issue by winged** [adfinis-sygroup/timed-backend#692]
We should have users assigned on various objects, to allow some more elaborate permissions and planning functions.

* Customers: Assigned users should then also be able to create / manage projects for this customer
* Projects: Assigned users should be able to manage tasks
* Tasks: Assigned users can be used for "light-weight" resource planning.

Ideally, I think each assignment should contain a "role" or "type" field to describe the relation (such as "manager", or "resource"). This way, one could be assigned to a project as a resource for planning purposes, or as a manager for permission purposes.

In a first step, only the assignment should be done - the permissions would probably best be done in a separate PR / feature.

**Comment by sbor23** [comment]
Can you elaborate a little what is meant by "planning functions"? What are the use cases here?

> Ideally, I think each assignment should contain a "role" or "type" field to describe the relation (such as "manager", or "resource"). This way, one could be assigned to a project as a resource for planning purposes, or as a manager for permission purposes.

I agree, this can be solved with extra fields on a through-table. Maybe we can specify already what the needed options are here. A set of boolean fields or maybe an enum?
