### ISSUE TITLE
Export Metrics

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/timed-backend#718]
We should expose application metrics to help us pinpoint performance or other issues.

The way to go seems to be [django-prometheus](https://github.com/korfuri/django-prometheus). The Prometheus metrics will integrate nicely with the Kube Prometheus Stack that is available for this on production.

Apart from exposing metrics in the backend we will also want to configure a `PodMonitor` to scrape them in the corresponding Helm chart.

* [x] django-prometheus
* [ ] `PodMonitor`

**Comment by sbor23** [comment]
See https://github.com/adfinis-sygroup/timed-backend/pull/719 for django-prometheus

**Comment by hairmare** [comment]
PodMonitor change is here: https://github.com/adfinis-sygroup/helm-charts/pull/225

It'll need a timed-backend release before I can get it ready to test though.
